const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
    username: {
        type: String,
        required: true,
        unique: true,
        trim: true,
        lowercase: true
    },
    salt: {
        type: String,
        required: true // The hex string generated by the frontend
    }
}, { timestamps: true });

module.exports = mongoose.model('User', userSchema);